### ISSUE TITLE
Add health metric to goal cards

### ISSUE THREAD

**Issue by narthur** [HabitFree/wp-accountability#52]
Express it as a percentage within a donut chart.

Simple moving average:
d = days of success in last year
health = (d / 360) * 100

Could also use a weighted moving average or exponential moving average:
http://daytrading.about.com/od/indicators/a/MovingAverages.htm
https://en.wikipedia.org/wiki/Moving_average#Weighted_moving_average
https://en.wikipedia.org/wiki/Moving_average#Exponential_moving_average

**Comment by Narthur** [comment]
Would be better if metric was actually % liklihood user will go the next week without a setback. This would be calculated as the inverse of the liklihood the user will have a setback during the next week, as calculated using machine learning based on all available features.

Possible features:
- Report history
- Partner interventions
- Partner report history
- Survey responses

Information:
- http://stats.stackexchange.com/questions/13335/feature-selection-for-low-probability-event-prediction
- https://en.wikipedia.org/wiki/Predictive_modelling
- https://www.quora.com/What-is-the-best-way-to-apply-Machine-Learning-algorithm-in-PHP-project-using-PHP-or-any-other-language-with-a-bridge-or-else
- http://stackoverflow.com/questions/12527595/how-to-apply-machine-learning-algorithm-in-php
- http://stackoverflow.com/questions/3050450/which-langauge-should-i-use-for-artificial-intelligence-on-web-projects
- http://phpir.com/support-vector-machines-in-php/

Possible tools:
- https://github.com/gburtini/Learning-Library-for-PHP
- https://bigml.com/developers
- http://php.net/manual/en/book.svm.php
- https://libraries.io/search?keywords=machine+learning&languages=PHP

**Comment by narthur** [comment]
Resolved
